#!/bin/bash

modelFile=$METAPHOR_DIR/models/farsiModels/farsiPOSModel/StanfordTagger/farsi.tagger.model.treebank
testFile=$METAPHOR_DIR/external-tools/farsiTools/POSTagger/testData/treebankForTagger
taggerDir=$METAPHOR_DIR/external-tools/farsiTools/POSTagger/stanford-postagger

cd $taggerDir

echo "current dir:"
echo `pwd`

java -mx2G  -classpath stanford-postagger.jar edu.stanford.nlp.tagger.maxent.MaxentTagger -prop models/farsiPropsFile.prop -model $modelFile -testFile $testFile

#for jmx
#mkdir $modelDir
#export CLASSPATH=$CLASSPATH:$taggerDir/mxpost.jar
#$taggerDir/trainmxpost $modelDir $inputFile
