#!/bin/sh

# Set these paths appropriately

BIN=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2/osx-intel/bin
CMD=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2/osx-intel/cmd
LIB=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2/osx-intel/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/bulgarian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
