#!/bin/sh

# Set these paths appropriately

BIN=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2/osx-intel/bin
CMD=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2/osx-intel/cmd
LIB=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2/osx-intel/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish.par
MWLFILE=${LIB}/spanish-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

