#!/bin/bash

MALTParserParameterDir=$METAPHOR_DIR/external-tools/farsiTools/MALTParser
MALTParserDir=$METAPHOR_DIR/external-tools/malt-1.5


testFile=$MALTParserParameterDir/testData/dependency.test.dashSeparated
modelFile=farsiMALTModel
outputFile=$MALTParserParameterDir/test.out

cd $MALTParserDir

java -mx2G -jar malt.jar -c $modelFile -i $testFile -m parse -o $outputFile
#java -jar malt.jar -c $modelFile -i $trainFile -m learn


