#!/bin/bash

echo "metaphor dir:"
echo $METAPHOR_DIR

MALTParserParameterDir=$METAPHOR_DIR/external-tools/farsiTools/MALTParser
MALTParserDir=$METAPHOR_DIR/external-tools/malt-1.5

trainFile=$MALTParserParameterDir/trainData/dependency.train.dashSeparated

cd $MALTParserDir
echo `pwd`

java -mx2G -jar malt.jar -c farsiMALTSmallModel -i $trainFile -m learn
#java -jar malt.jar -c $modelFile -i $trainFile -m learn


