#!/bin/bash

echo "currentDir:"
echo `pwd`

MALTParserParameterDir=$METAPHOR_DIR/external-tools/farsiTools/MALTParser
MALTParserDir=$METAPHOR_DIR/external-tools/malt-1.5

trainFile=$MALTParserParameterDir/trainData/dependency.train.dashSeparated
modelFile=$METAPHOR_DIR/models/farsiModels/farsiParseModel/farsi.malt.model

cd $MALTParserDir
echo `pwd`

java -mx2G -jar malt.jar -c farsiMALTModel -i $trainFile -m learn
#java -jar malt.jar -c $modelFile -i $trainFile -m learn


