#!/bin/bash

inputFile=$1
taggedFile=$1.tagged.txt
modifiedTaggedFile=$1.modified.tagged.txt
parserOutputFileName=$1.parsed.txt

taggerDir=`pwd`/POSTagger/jmx
parserDir=`pwd`/mstparser
taggedFileModifier=`pwd`/taggedFileModifier.py

POSmodelDir=`pwd`/models/farsiPOSModel
depModelFile=`pwd`/models/farsi.dep.model

#POS tag the input file
export CLASSPATH=$CLASSPATH:$taggerDir/mxpost.jar
$taggerDir/mxpost $POSmodelDir < $inputFile > $taggedFile

#modify the POS tagged file to include dummy label & dep lines
python $taggedFileModifier $taggedFile $modifiedTaggedFile


#run parser
cd $parserDir
java -classpath ".:lib/trove.jar" -Xmx1800m mstparser.DependencyParser test model-name:$depModelFile test-file:$modifiedTaggedFile output-file:$parserOutputFileName
