#!/bin/bash

farsiPipelineDir=$METAPHOR_DIR/pipelines/Farsi

parserOutputFileName="${1:-/dev/stdin}"
LFFileName="${2:-/dev/stdout}"

parseToLFConverter=$farsiPipelineDir/convertParseTreeToLF.py
farsiWordsDict=$farsiPipelineDir/farsiWordsForLFCreation.txt


# convert the parse results to LF
python $parseToLFConverter $parserOutputFileName $LFFileName $farsiWordsDict
