#!/bin/bash

inputFile="${1:-/dev/stdin}"
outputFileName="${2:-/dev/stdout}"

farsiPipelineDir=$METAPHOR_DIR/pipelines/Farsi

$farsiPipelineDir/tokenize < $inputFile |$farsiPipelineDir/tag |$farsiPipelineDir/parse|$farsiPipelineDir/createLF > $outputFileName