#!/bin/bash

inputFile="${1:-/dev/stdin}"
outputFileName="${2:-/dev/stdout}"

farsiPipelineDir=$METAPHOR_DIR/pipelines/Farsi

if [ -d "$2" ]; then
	$farsiPipelineDir/tokenize < $inputFile | 
	tee $2/tokenizer_o.txt |
	$farsiPipelineDir/addDot.py |
	tee $2/dot_o.txt |
	$farsiPipelineDir/tag |
	tee $2/tagger_o.txt |
	$farsiPipelineDir/parse |
	tee $2/parser_o.txt |
	$farsiPipelineDir/createLF > /dev/stdout
else
	$farsiPipelineDir/tokenize < $inputFile | 
	$farsiPipelineDir/addDot.py |
	$farsiPipelineDir/tag |
	$farsiPipelineDir/parse |
	$farsiPipelineDir/createLF > $outputFileName
fi