#!/bin/sh

# Set these paths appropriately

BIN=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2-linux-64bit/bin
CMD=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2-linux-64bit/cmd
LIB=/Users/zvm/code/nlp/Metaphor-ADP/external-tools/tree-tagger-3.2-linux-64bit/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
